[build]
  functions = "./functions" 


  [[redirects]]
  from = "/
  to = "/bridgettstuhlmiller.denovorealty.com"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}